### ISSUE TITLE
Add the 2050.txt in the github repo, rather than comment.

### ISSUE THREAD

**Issue by adiultra** [CPP-Coders/Phantom#2]
Do add the `2050.txt` in the github repo, Its wierd the person would really scroll to that. Or, you could create the file with the program itself. :+1:

**Comment by arcdwi** [comment]
Oh Yes! I definitely do agree with you. And shall soon find out a better way for it. Probably with some further mutations and variations. :+1:

**Comment by adiultra** [comment]
Now since the issue is resolved I am :smile:

**Comment by arcdwi** [comment]
Any time...
